import type { Card } from "$lib";

export const allCards: Card[] = [
  {
    src: "cards/gateway-station.jpg",
    name: "Gateway Station",
    cost: 2,
    vp: 1,
    powers: ["IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "START_BLUE",
    },
  },
  {
    src: "cards/abandoned-mine-squatters.jpg",
    name: "Abandoned Mine Squatters",
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/terraforming-colonists.jpg",
    name: "Terraforming Colonists",
    cost: 2,
    vp: 1,
    powers: ["III", "V"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/galactic-trade-emissaries.jpg",
    name: "Galactic Trade Emissaries",
    cost: 2,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      type: "START_RED",
    },
  },
  {
    src: "cards/industrial-robots.jpg",
    name: "Industrial Robots",
    cost: 2,
    vp: 1,
    powers: ["II", "V"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/star-nomad-raiders.jpg",
    name: "Star Nomad Raiders",
    cost: 2,
    vp: 1,
    powers: ["III", "$"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/old-earth.jpg",
    name: "Old Earth",
    cost: 3,
    vp: 2,
    powers: ["$", "IV"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/epsilon-eridani.jpg",
    name: "Epsilon Eridani",
    cost: 2,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      type: "START_RED",
    },
  },
  {
    src: "cards/alpha-centauri.jpg",
    name: "Alpha Centauri",
    cost: 2,
    vp: 0,
    powers: ["III"],
    world: {
      good: "RARE",
      isWindfall: true,
      type: "START_BLUE",
    },
  },
  {
    src: "cards/new-sparta.jpg",
    name: "New Sparta",
    cost: 2,
    vp: 1,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/earths-lost-colony.jpg",
    name: "Earth's Lost Colony",
    cost: 2,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      type: "START_BLUE",
    },
  },
  {
    src: "cards/rebel-fuel-cache.jpg",
    name: "Rebel Fuel Cache",
    keywords: ["REBEL"],
    cost: 1,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/public-works.jpg",
    name: "Public Works",
    cost: 1,
    vp: 1,
    powers: ["II", "IV"],
  },
  {
    src: "cards/gem-world.jpg",
    name: "Gem World",
    cost: 2,
    vp: 1,
    powers: ["V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/colony-ship.jpg",
    name: "Colony Ship",
    cost: 2,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/comet-zone.jpg",
    name: "Comet Zone",
    cost: 3,
    vp: 2,
    powers: ["V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/expedition-force.jpg",
    name: "Expedition Force",
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
  },
  {
    src: "cards/mining-robots.jpg",
    name: "Mining Robots",
    cost: 2,
    vp: 1,
    powers: ["III", "V"],
  },
  {
    src: "cards/rebel-miners.jpg",
    name: "Rebel Miners",
    keywords: ["REBEL"],
    cost: 2,
    vp: 1,
    powers: ["V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
  },
  {
    src: "cards/export-duties.jpg",
    name: "Export Duties",
    cost: 1,
    vp: 1,
    powers: ["$"],
  },
  {
    src: "cards/former-penal-colony.jpg",
    name: "Former Penal Colony",
    cost: 2,
    vp: 1,
    powers: ["III"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/malevolent-lifeforms.jpg",
    name: "Malevolent Lifeforms",
    cost: 4,
    vp: 2,
    powers: ["I", "V"],
    world: {
      good: "GENE",
      isMilitary: true,
    },
  },
  {
    src: "cards/new-military-tactics.jpg",
    name: "New Military Tactics",
    cost: 1,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/space-marines.jpg",
    name: "Space Marines",
    cost: 2,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/contact-specialist.jpg",
    name: "Contact Specialist",
    cost: 1,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/avian-uplift-race.jpg",
    name: "Avian Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/spice-world.jpg",
    name: "Spice World",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/lost-species-ark-world.jpg",
    name: "Lost Species Ark World",
    cost: 5,
    vp: 3,
    powers: ["V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/new-vinland.jpg",
    name: "New Vinland",
    cost: 2,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/artist-colony.jpg",
    name: "Artist Colony",
    cost: 1,
    vp: 1,
    powers: ["V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/alien-robotic-factory.jpg",
    name: "Alien Robotic Factory",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 5,
    powers: ["V"],
    world: {
      good: "ALIEN",
    },
  },
  {
    src: "cards/plague-world.jpg",
    name: "Plague World",
    cost: 3,
    vp: 0,
    powers: ["IV", "V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/distant-world.jpg",
    name: "Distant World",
    cost: 4,
    vp: 2,
    powers: ["$", "V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/rebel-outpost.jpg",
    name: "Rebel Outpost",
    keywords: ["REBEL"],
    cost: 5,
    vp: 5,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/rebel-warrior-race.jpg",
    name: "Rebel Warrior Race",
    keywords: ["REBEL"],
    cost: 3,
    vp: 2,
    powers: ["III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/rebel-underground.jpg",
    name: "Rebel Underground",
    keywords: ["REBEL"],
    cost: 3,
    vp: 4,
    powers: ["V"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/new-survivalists.jpg",
    name: "New Survivalists",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
    },
  },
  {
    src: "cards/outlaw-world.jpg",
    name: "Outlaw World",
    cost: 1,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/lost-alien-battle-fleet.jpg",
    name: "Lost Alien Battle Fleet",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
      isMilitary: true,
    },
  },
  {
    src: "cards/diversified-economy.jpg",
    name: "Diversified Economy",
    cost: 4,
    vp: 2,
    powers: ["IV", "V"],
  },
  {
    src: "cards/consumer-markets.jpg",
    name: "Consumer Markets",
    cost: 5,
    vp: 3,
    powers: ["IV", "V"],
  },
  {
    src: "cards/mining-conglomerate.jpg",
    name: "Mining Conglomerate",
    cost: 3,
    vp: 2,
    powers: ["$", "IV", "V"],
  },
  {
    src: "cards/research-labs.jpg",
    name: "Research Labs",
    cost: 4,
    vp: 2,
    powers: ["I", "IV", "V"],
  },
  {
    src: "cards/deficit-spending.jpg",
    name: "Deficit Spending",
    cost: 2,
    vp: 1,
    powers: ["IV"],
  },
  {
    src: "cards/investment-credits.jpg",
    name: "Investment Credits",
    cost: 1,
    vp: 1,
    powers: ["II"],
  },
  {
    src: "cards/pan-galactic-league.jpg",
    name: "Pan-Galactic League",
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
  },
  {
    src: "cards/mining-league.jpg",
    name: "Mining League",
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
  },
  {
    src: "cards/free-trade-association.jpg",
    name: "Free Trade Association",
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
  },
  {
    src: "cards/alien-tech-institute.jpg",
    name: "Alien Tech Institute",
    keywords: ["ALIEN"],
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/galactic-survey-seti.jpg",
    name: "Galactic Survey: SETI",
    cost: 6,
    vp: "?",
    powers: ["I"],
  },
  {
    src: "cards/galactic-federation.jpg",
    name: "Galactic Federation",
    cost: 6,
    vp: "?",
    powers: ["II"],
  },
  {
    src: "cards/refugee-world.jpg",
    name: "Refugee World",
    cost: 0,
    vp: 1,
    powers: ["III"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
  },
  {
    src: "cards/empath-world.jpg",
    name: "Empath World",
    cost: 1,
    vp: 1,
    powers: ["III"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
  },
  {
    src: "cards/galactic-resort.jpg",
    name: "Galactic Resort",
    cost: 3,
    vp: 2,
    powers: ["IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
  },
  {
    src: "cards/pre-sentient-race.jpg",
    name: "Pre-Sentient Race",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "GENE",
      isWindfall: true,
    },
  },
  {
    src: "cards/deserted-alien-outpost.jpg",
    name: "Deserted Alien Outpost",
    keywords: ["ALIEN"],
    cost: 4,
    vp: 3,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/deserted-alien-colony.jpg",
    name: "Deserted Alien Colony",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 4,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/galactic-engineers.jpg",
    name: "Galactic Engineers",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {},
  },
  {
    src: "cards/black-market-trading-world.jpg",
    name: "Black Market Trading World",
    cost: 2,
    vp: 1,
    powers: ["$"],
    world: {},
  },
  {
    src: "cards/merchant-world.jpg",
    name: "Merchant World",
    cost: 4,
    vp: 2,
    powers: ["$", "IV"],
    world: {},
  },
  {
    src: "cards/tourist-world.jpg",
    name: "Tourist World",
    cost: 4,
    vp: 2,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/galactic-trendsetters.jpg",
    name: "Galactic Trendsetters",
    cost: 5,
    vp: 3,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/alien-rosetta-stone-world.jpg",
    name: "Alien Rosetta Stone World",
    keywords: ["ALIEN"],
    cost: 3,
    vp: 3,
    powers: ["III", "V"],
    world: {},
  },
  {
    src: "cards/star-nomad-lair.jpg",
    name: "Star Nomad Lair",
    cost: 1,
    vp: 1,
    powers: ["I", "$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/the-last-of-the-uplift-gnarssh.jpg",
    name: "The Last of the Uplift Gnarssh",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 1,
    vp: 0,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/alien-robot-sentry.jpg",
    name: "Alien Robot Sentry",
    keywords: ["ALIEN"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/pirate-world.jpg",
    name: "Pirate World",
    cost: 3,
    vp: 2,
    powers: ["$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/reptilian-uplift-race.jpg",
    name: "Reptilian Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/lost-alien-warship.jpg",
    name: "Lost Alien Warship",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 3,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/alien-robot-scout-ship.jpg",
    name: "Alien Robot Scout Ship",
    keywords: ["ALIEN"],
    cost: 4,
    vp: 2,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/runaway-robots.jpg",
    name: "Runaway Robots",
    cost: 1,
    vp: 1,
    powers: ["V"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/interstellar-bank.jpg",
    name: "Interstellar Bank",
    cost: 2,
    vp: 1,
    powers: ["II"],
  },
  {
    src: "cards/terraforming-robots.jpg",
    name: "Terraforming Robots",
    keywords: ["TERRAFORMING"],
    cost: 3,
    vp: 2,
    powers: ["III", "IV"],
  },
  {
    src: "cards/drop-ships.jpg",
    name: "Drop Ships",
    cost: 4,
    vp: 2,
    powers: ["III"],
  },
  {
    src: "cards/new-galactic-order.jpg",
    name: "New Galactic Order",
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/asteroid-belt.jpg",
    name: "Asteroid Belt",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/merchant-guild.jpg",
    name: "Merchant Guild",
    cost: 6,
    vp: "?",
    powers: ["V"],
  },
  {
    src: "cards/secluded-world.jpg",
    name: "Secluded World",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/imperium-armaments-world.jpg",
    name: "Imperium Armaments World",
    keywords: ["IMPERIUM"],
    cost: 3,
    vp: 2,
    powers: ["III", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/terraformed-world.jpg",
    name: "Terraformed World",
    cost: 5,
    vp: 5,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/replicant-robots.jpg",
    name: "Replicant Robots",
    cost: 4,
    vp: 2,
    powers: ["III"],
  },
  {
    src: "cards/pilgrimage-world.jpg",
    name: "Pilgrimage World",
    cost: 0,
    vp: 2,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/rebel-homeworld.jpg",
    name: "Rebel Homeworld",
    keywords: ["REBEL"],
    cost: 7,
    vp: 7,
    powers: [],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/new-economy.jpg",
    name: "New Economy",
    cost: 6,
    vp: "?",
    powers: ["IV"],
  },
  {
    src: "cards/radioactive-world.jpg",
    name: "Radioactive World",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/aquatic-uplift-race.jpg",
    name: "Aquatic Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/genetics-lab.jpg",
    name: "Genetics Lab",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
  },
  {
    src: "cards/bio-hazard-mining-world.jpg",
    name: "Bio-Hazard Mining World",
    cost: 2,
    vp: 0,
    powers: ["$", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/deserted-alien-library.jpg",
    name: "Deserted Alien Library",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 5,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/destroyed-world.jpg",
    name: "Destroyed World",
    cost: 1,
    vp: 0,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/galactic-renaissance.jpg",
    name: "Galactic Renaissance",
    cost: 6,
    vp: "?",
    powers: ["I"],
  },
  {
    src: "cards/blaster-gem-mines.jpg",
    name: "Blaster Gem Mines",
    cost: 3,
    vp: 2,
    powers: ["III"],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/gambling-world.jpg",
    name: "Gambling World",
    cost: 1,
    vp: 1,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/expanding-colony.jpg",
    name: "Expanding Colony",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {},
  },
  {
    src: "cards/space-port.jpg",
    name: "Space Port",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/prosperous-world.jpg",
    name: "Prosperous World",
    cost: 3,
    vp: 2,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/new-earth.jpg",
    name: "New Earth",
    cost: 5,
    vp: 3,
    powers: ["IV", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/rebel-base.jpg",
    name: "Rebel Base",
    keywords: ["REBEL"],
    cost: 6,
    vp: 6,
    powers: [],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/galactic-imperium.jpg",
    name: "Galactic Imperium",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/trade-league.jpg",
    name: "Trade League",
    cost: 6,
    vp: "?",
    powers: ["$"],
  },
  {
    src: "cards/mining-world.jpg",
    name: "Mining World",
    cost: 3,
    vp: 2,
    powers: ["V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/alien-first-contact-team.jpg",
    name: "Alien First Contact Team",
    keywords: ["ALIEN"],
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/starry-rift-pioneers.jpg",
    name: "Starry Rift Pioneers",
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "START_BLUE",
    },
    set: "xi",
  },
  {
    src: "cards/rebel-cadre.jpg",
    name: "Rebel Cadre",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["III", "IV"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/terraforming-surveyors.jpg",
    name: "Terraforming Surveyors",
    keywords: ["TERRAFORMING"],
    cost: 2,
    vp: 0,
    powers: ["I", "$"],
    world: {
      type: "START_BLUE",
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-defense-post.jpg",
    name: "Anti-Xeno Defense Post",
    cost: 2,
    vp: 2,
    powers: ["III", "V"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/uplift-descendants.jpg",
    name: "Uplift Descendants",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 1,
    vp: 0,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-embassy.jpg",
    name: "Anti-Xeno Embassy",
    cost: 2,
    vp: 1,
    powers: ["III", "IV", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xi",
  },
  {
    src: "cards/novelty-peddlers.jpg",
    name: "Novelty Peddlers",
    cost: 2,
    vp: 1,
    powers: ["III", "$", "IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/galactic-clearing-house.jpg",
    name: "Galactic Clearing House",
    cost: 5,
    vp: 3,
    powers: ["$", "IV", "V"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-black-market-gangs.jpg",
    name: "Rebel Black Market Gangs",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["III", "$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-hostage-planet.jpg",
    name: "Xeno Hostage Planet",
    keywords: ["XENO"],
    cost: 5,
    vp: 4,
    powers: [],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/terraforming-uplift-project.jpg",
    name: "Terraforming Uplift Project",
    keywords: ["UPLIFT", "TERRAFORMING", "CHROMO"],
    cost: 2,
    vp: 0,
    powers: ["IV"],
    world: {
      good: "RARE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/corrosive-uplift-world.jpg",
    name: "Corrosive Uplift World",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 3,
    vp: "?",
    powers: ["IV", "V"],
    world: {
      good: "RARE",
    },
    set: "xi",
  },
  {
    src: "cards/imperium-munitions-inc.jpg",
    name: "Imperium Munitions, Inc.",
    keywords: ["IMPERIUM"],
    cost: 5,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "RARE",
    },
    set: "xi",
  },
  {
    src: "cards/rebel-bunker.jpg",
    name: "Rebel Bunker",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["I", "III"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-held-imperium-mine.jpg",
    name: "Xeno-Held Imperium Mine",
    keywords: ["IMPERIUM", "XENO"],
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-resistance.jpg",
    name: "Rebel Resistance",
    keywords: ["REBEL"],
    cost: 3,
    vp: 1,
    powers: ["I", "III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-refugees.jpg",
    name: "Anti-Xeno Refugees",
    cost: 2,
    vp: 0,
    powers: ["III"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/pan-galactic-disease-center.jpg",
    name: "Pan-Galactic Disease Center",
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "GENE",
    },
    set: "xi",
  },
  {
    src: "cards/adaptable-uplift-race.jpg",
    name: "Adaptable Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 4,
    vp: 2,
    powers: ["IV"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-infested-uplift-world.jpg",
    name: "Xeno-Infested Uplift World",
    keywords: ["UPLIFT", "XENO", "CHROMO"],
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-colony.jpg",
    name: "Xeno Colony",
    keywords: ["XENO"],
    cost: 4,
    vp: 2,
    powers: ["V"],
    world: {
      good: "GENE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/uplift-coalition.jpg",
    name: "Uplift Coalition",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 4,
    vp: "?",
    powers: ["I", "III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-alien-bunker.jpg",
    name: "Anti-Xeno Alien Bunker",
    keywords: ["ALIEN"],
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
    },
    set: "xi",
  },
  {
    src: "cards/alien-archives.jpg",
    name: "Alien Archives",
    cost: 5,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
    },
    set: "xi",
  },
  {
    src: "cards/alien-weapon-cache.jpg",
    name: "Alien Weapon Cache",
    keywords: ["ALIEN"],
    cost: 3,
    vp: 1,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-infested-alien-outpost.jpg",
    name: "Xeno-Infested Alien Outpost",
    keywords: ["ALIEN", "XENO"],
    cost: 7,
    vp: 5,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/alien-defense-center.jpg",
    name: "Alien Defense Center",
    keywords: ["ALIEN"],
    cost: 8,
    vp: 8,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-warrior-colony.jpg",
    name: "Xeno Warrior Colony",
    keywords: ["XENO"],
    cost: 6,
    vp: 5,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-occupied-rebel-world.jpg",
    name: "Xeno-Occupied Rebel World",
    keywords: ["REBEL", "XENO"],
    cost: 8,
    vp: 7,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-forward-command.jpg",
    name: "Xeno Forward Command",
    keywords: ["XENO"],
    cost: 9,
    vp: 9,
    powers: [],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-militia.jpg",
    name: "Anti-Xeno Militia",
    cost: 1,
    vp: 0,
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/alien-weapon-plans.jpg",
    name: "Alien Weapon Plans",
    keywords: ["ALIEN"],
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
    set: "xi",
  },
  {
    src: "cards/uplift-terraforming.jpg",
    name: "Uplift Terraforming",
    keywords: ["UPLIFT", "TERRAFORMING"],
    cost: 2,
    vp: 1,
    powers: ["I", "III", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-assault-troops.jpg",
    name: "Anti-Xeno Assault Troops",
    cost: 3,
    vp: 2,
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/imperium-arms-factory.jpg",
    name: "Imperium Arms Factory",
    keywords: ["IMPERIUM"],
    cost: 4,
    vp: 2,
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/construction-corps.jpg",
    name: "Construction Corps",
    cost: 4,
    vp: 2,
    powers: ["II", "V"],
    set: "xi",
  },
  {
    src: "cards/galactic-home-front.jpg",
    name: "Galactic Home Front",
    cost: 5,
    vp: 3,
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/uplift-bio-engineers.jpg",
    name: "Uplift Bio-Engineers",
    keywords: ["UPLIFT"],
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
    set: "xi",
  },
  {
    src: "cards/imperium-war-profiteers.jpg",
    name: "Imperium War Profiteers",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
    set: "xi",
  },
  {
    src: "cards/terraforming-defenders.jpg",
    name: "Terraforming Defenders",
    keywords: ["TERRAFORMING"],
    cost: 6,
    vp: "?",
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-rebel-force.jpg",
    name: "Anti-Xeno Rebel Force",
    keywords: ["REBEL"],
    cost: 6,
    vp: "?",
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/alien-historians.jpg",
    name: "Alien Historians",
    keywords: ["ALIEN"],
    cost: 6,
    vp: "?",
    powers: ["I", "III", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-league.jpg",
    name: "Anti-Xeno League",
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
    set: "xi",
  },
];
