import type { Card } from "$lib";

export const allCards: Card[] = [
  {
    src: "cards/xeno-sentry-world.jpg",
    name: "xeno sentry world",
    keywords: ["XENO"],
    cost: 3,
    vp: 2,
    powers: ["I"],
    world: {
      isMilitary: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-warrior-clutch.jpg",
    name: "xeno warrior clutch",
    keywords: ["XENO"],
    cost: 4,
    vp: 4,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/pirate-lair.jpg",
    name: "pirate lair",
    cost: 3,
    vp: 3,
    powers: ["III", "$", "V"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-occupied-rebel-supply.jpg",
    name: "xeno-occupied rebel supply",
    keywords: ["XENO", "REBEL"],
    cost: 5,
    vp: 3,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/outlaw-rebel-mines.jpg",
    name: "outlaw rebel mines",
    keywords: ["REBEL"],
    cost: 2,
    vp: 2,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/anti-xeno-uplift-warriors.jpg",
    name: "anti-xeno uplift warriors",
    keywords: ["CHROMO", "ANTI-XENO", "UPLIFT"],
    cost: 2,
    vp: 0,
    powers: ["III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-scouting-force.jpg",
    name: "xeno scouting force",
    keywords: ["XENO"],
    cost: 3,
    vp: 2,
    powers: ["III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-held-alien-sentry-post.jpg",
    name: "xeno-held alien sentry post",
    keywords: ["XENO", "ALIEN"],
    cost: 2,
    vp: 2,
    powers: ["I", "III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-held-alien-ruins.jpg",
    name: "xeno-held alien ruins",
    keywords: ["XENO", "ALIEN"],
    cost: 5,
    vp: 3,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/alien-warning-beacon.jpg",
    name: "alien warning beacon",
    keywords: ["ALIEN"],
    cost: 1,
    vp: 4,
    powers: ["III", "V"],
    world: {
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/scavenger-world.jpg",
    name: "scavenger world",
    cost: 1,
    vp: 1,
    powers: ["III", "$", "V"],
    world: {
      good: "NOVELTY",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/frontier-settlement.jpg",
    name: "frontier settlement",
    cost: 2,
    vp: 2,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/monastery-world.jpg",
    name: "monastery world",
    cost: 3,
    vp: 2,
    powers: ["II", "III", "IV", "V"],
    world: {
      good: "NOVELTY",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/outlaw-claim-jumpers.jpg",
    name: "outlaw claim jumpers",
    cost: 1,
    vp: 0,
    powers: ["III", "$", "IV"],
    world: {
      good: "RARE",
      isWindfall: true,
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/rebel-mining-outpost.jpg",
    name: "rebel mining outpost",
    keywords: ["REBEL"],
    cost: 3,
    vp: 2,
    powers: ["III", "IV", "V"],
    world: {
      good: "RARE",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/outlaw-uplift-geneticists.jpg",
    name: "outlaw uplift geneticists",
    keywords: ["UPLIFT"],
    cost: 4,
    vp: 0,
    powers: ["IV", "V"],
    world: {
      good: "GENE",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/uplift-cloning-extremists.jpg",
    name: "uplift cloning extremists",
    keywords: ["UPLIFT"],
    cost: 4,
    vp: 2,
    powers: ["$", "V"],
    world: {
      good: "GENE",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/clandestine-alien-researchers.jpg",
    name: "clandestine alien researchers",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 4,
    powers: ["II", "IV", "V"],
    world: {
      good: "ALIEN",
      type: "NEAR",
    },
    set: "xc",
  },
  {
    src: "cards/run-amok-robots.jpg",
    name: "run-amok robots",
    cost: 6,
    vp: 4,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-held-populous-world.jpg",
    name: "xeno-held populous world",
    keywords: ["XENO"],
    cost: 7,
    vp: 5,
    powers: ["IV"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/imperium-warlord-keep.jpg",
    name: "imperium warlord keep",
    keywords: ["IMPERIUM"],
    cost: 7,
    vp: 7,
    powers: ["III", "V"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-staging-point.jpg",
    name: "xeno staging point",
    keywords: ["XENO"],
    cost: 8,
    vp: 7,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-rebel-battleground.jpg",
    name: "xeno-rebel battleground",
    keywords: ["XENO", "REBEL"],
    cost: 8,
    vp: 7,
    powers: ["V"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-hidden-command.jpg",
    name: "xeno hidden command",
    keywords: ["XENO"],
    cost: 9,
    vp: 8,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-embattled-colony.jpg",
    name: "xeno-embattled colony",
    keywords: ["XENO"],
    cost: 7,
    vp: 5,
    powers: ["III", "V"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/rebel-final-refuge.jpg",
    name: "rebel final refuge",
    keywords: ["REBEL"],
    cost: 9,
    vp: 7,
    powers: ["III"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-occupied-mining-colony.jpg",
    name: "xeno-occupied mining colony",
    keywords: ["XENO"],
    cost: 6,
    vp: 4,
    powers: ["IV", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/hidden-imperium-slave-mines.jpg",
    name: "hidden imperium slave mines",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: 5,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/xeno-breeding-world-husk.jpg",
    name: "xeno breeding world husk",
    keywords: ["XENO"],
    cost: 6,
    vp: 5,
    powers: ["III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/rebel-uplift-warrior-colony.jpg",
    name: "rebel uplift warrior colony",
    keywords: ["CHROMO", "REBEL", "UPLIFT"],
    cost: 7,
    vp: 6,
    powers: ["III", "V"],
    world: {
      good: "GENE",
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/alien-anti-xeno-guardians.jpg",
    name: "alien anti-xeno guardians",
    keywords: ["ALIEN", "ANTI-XENO"],
    cost: 8,
    vp: 7,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/alien-anti-xeno-stockpile.jpg",
    name: "alien anti-xeno stockpile",
    keywords: ["ALIEN", "ANTI-XENO"],
    cost: 10,
    vp: 8,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/frontier-surveyors.jpg",
    name: "frontier surveyors",
    cost: 5,
    vp: 5,
    powers: ["I", "III", "IV"],
    world: {
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/deep-space-terraforming.jpg",
    name: "deep space terraforming",
    keywords: ["TERRAFORMING"],
    cost: 6,
    vp: 5,
    powers: ["I", "III", "V"],
    world: {
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/federation-frontier-hq.jpg",
    name: "federation frontier hq",
    cost: 7,
    vp: 7,
    powers: ["II", "III", "IV"],
    world: {
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/mega-exclusive-resort.jpg",
    name: "mega-exclusive resort",
    cost: 8,
    vp: 8,
    powers: ["IV"],
    world: {
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/illicit-uplift-collector.jpg",
    name: "illicit-uplift-collector",
    keywords: ["CHROMO", "UPLIFT"],
    cost: 6,
    vp: 5,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/alien-ruins-settlement.jpg",
    name: "alien ruins settlement",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 4,
    powers: ["$", "IV", "V"],
    world: {
      good: "NOVELTY",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/successful-pioneer-world.jpg",
    name: "successful pioneer world",
    cost: 6,
    vp: 6,
    powers: ["II", "III", "V"],
    world: {
      good: "NOVELTY",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/terraforming-claim-jumpers.jpg",
    name: "terraforming claim jumpers",
    keywords: ["TERRAFORMING"],
    cost: 5,
    vp: 4,
    powers: ["III", "IV"],
    world: {
      good: "RARE",
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/deserted-alien-mine.jpg",
    name: "deserted alien mine",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 5,
    powers: ["IV", "V"],
    world: {
      good: "RARE",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/outlaw-arms-producer.jpg",
    name: "outlaw arms producer",
    cost: 7,
    vp: 5,
    powers: ["III", "IV", "V"],
    world: {
      good: "RARE",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/anti-xeno-uplift-base.jpg",
    name: "anti-xeno uplift base",
    keywords: ["CHROMO", "ANTI-XENO", "UPLIFT"],
    cost: 5,
    vp: 6,
    powers: ["III", "V"],
    world: {
      good: "GENE",
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/clandestine-uplift-facility.jpg",
    name: "clandestine uplift facility",
    keywords: ["CHROMO", "UPLIFT"],
    cost: 7,
    vp: 5,
    powers: ["IV", "V"],
    world: {
      good: "GENE",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/alien-lift-ring-cache.jpg",
    name: "alien lift-ring cache",
    keywords: ["ALIEN"],
    cost: 9,
    vp: 8,
    powers: ["IV"],
    world: {
      good: "ALIEN",
      isWindfall: true,
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/deserted-alien-weapons-factory.jpg",
    name: "deserted alien weapons factory",
    keywords: ["ALIEN"],
    cost: 7,
    vp: 6,
    powers: ["I", "III", "V"],
    world: {
      good: "ALIEN",
      type: "FAR",
    },
    set: "xc",
  },
  {
    src: "cards/rebel-cadre.jpg",
    name: "Rebel Cadre",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["III", "IV"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/alien-first-contact-team.jpg",
    name: "Alien First Contact Team",
    keywords: ["ALIEN"],
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/anti-xeno-resistance.jpg",
    name: "anti-xeno resistance",
    keywords: ["ANTI-XENO"],
    cost: 1,
    vp: 1,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xc",
  },
  {
    src: "cards/defense-systems-inc.jpg",
    name: "defense systems, inc.",
    cost: 1,
    vp: 1,
    powers: ["II", "III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xc",
  },
  {
    src: "cards/new-sparta.jpg",
    name: "New Sparta",
    cost: 2,
    vp: 1,
    powers: ["III"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/star-nomad-raiders.jpg",
    name: "Star Nomad Raiders",
    cost: 2,
    vp: 1,
    powers: ["III", "$"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/anti-xeno-defense-post.jpg",
    name: "Anti-Xeno Defense Post",
    keywords: ["ANTI-XENO"],
    cost: 2,
    vp: 2,
    powers: ["III", "V"],
    world: {
      isMilitary: true,
      type: "START_RED",
    },
    set: "xi",
  },
  {
    src: "cards/imperium-blaster-gem-prospectors.jpg",
    name: "imperium blaster gem prospectors",
    keywords: ["IMPERIUM"],
    cost: 1,
    vp: 0,
    powers: ["III"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
      type: "START_RED",
    },
    set: "xc",
  },
  {
    src: "cards/abandoned-mine-squatters.jpg",
    name: "Abandoned Mine Squatters",
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
      type: "START_RED",
    },
  },
  {
    src: "cards/galactic-trade-emissaries.jpg",
    name: "Galactic Trade Emissaries",
    cost: 2,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      type: "START_RED",
    },
  },
  {
    src: "cards/epsilon-eridani.jpg",
    name: "Epsilon Eridani",
    cost: 2,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      type: "START_RED",
    },
  },
  {
    src: "cards/terraforming-surveyors.jpg",
    name: "Terraforming Surveyors",
    keywords: ["TERRAFORMING"],
    cost: 2,
    vp: 0,
    powers: ["I", "$"],
    world: {
      type: "START_BLUE",
    },
    set: "xi",
  },
  {
    src: "cards/industrial-robots.jpg",
    name: "Industrial Robots",
    cost: 2,
    vp: 1,
    powers: ["II", "V"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/terraforming-colonists.jpg",
    name: "Terraforming Colonists",
    keywords: ["TERRAFORMING"],
    cost: 2,
    vp: 1,
    powers: ["III", "V"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/old-earth.jpg",
    name: "Old Earth",
    cost: 3,
    vp: 2,
    powers: ["$", "IV"],
    world: {
      type: "START_BLUE",
    },
  },
  {
    src: "cards/star-nomad-trading-post.jpg",
    name: "star nomad trading post",
    cost: 1,
    vp: 1,
    powers: ["I", "III", "$"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "START_BLUE",
    },
    set: "xc",
  },
  {
    src: "cards/starry-rift-pioneers.jpg",
    name: "Starry Rift Pioneers",
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "START_BLUE",
    },
    set: "xi",
  },
  {
    src: "cards/gateway-station.jpg",
    name: "Gateway Station",
    cost: 2,
    vp: 1,
    powers: ["IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
      type: "START_BLUE",
    },
  },
  {
    src: "cards/earths-lost-colony.jpg",
    name: "Earth's Lost Colony",
    cost: 2,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      type: "START_BLUE",
    },
  },
  {
    src: "cards/alpha-centauri.jpg",
    name: "Alpha Centauri",
    cost: 2,
    vp: 0,
    powers: ["III"],
    world: {
      good: "RARE",
      isWindfall: true,
      type: "START_BLUE",
    },
  },
  {
    src: "cards/frontier-miners.jpg",
    name: "frontier miners",
    cost: 2,
    vp: 1,
    powers: ["I", "III", "V"],
    world: {
      good: "RARE",
      type: "START_BLUE",
    },
    set: "xc",
  },
  {
    src: "cards/terraforming-bio-engineers.jpg",
    name: "terraforming bio-engineers",
    keywords: ["TERRAFORMING"],
    cost: 2,
    vp: 1,
    powers: ["III", "$", "V"],
    world: {
      good: "GENE",
      type: "START_BLUE",
    },
    set: "xc",
  },
  {
    src: "cards/outlaw-world.jpg",
    name: "Outlaw World",
    cost: 1,
    vp: 1,
    powers: ["III", "IV"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/rebel-underground.jpg",
    name: "Rebel Underground",
    keywords: ["REBEL"],
    cost: 3,
    vp: 4,
    powers: ["V"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/rebel-outpost.jpg",
    name: "Rebel Outpost",
    keywords: ["REBEL"],
    cost: 5,
    vp: 5,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/xeno-warrior-colony.jpg",
    name: "Xeno Warrior Colony",
    keywords: ["XENO"],
    cost: 6,
    vp: 5,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-base.jpg",
    name: "Rebel Base",
    keywords: ["REBEL"],
    cost: 6,
    vp: 6,
    powers: [],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/rebel-homeworld.jpg",
    name: "Rebel Homeworld",
    keywords: ["REBEL"],
    cost: 7,
    vp: 7,
    powers: [],
    world: {
      isMilitary: true,
    },
  },
  {
    src: "cards/xeno-occupied-rebel-world.jpg",
    name: "Xeno-Occupied Rebel World",
    keywords: ["REBEL", "XENO"],
    cost: 8,
    vp: 7,
    powers: ["III"],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-forward-command.jpg",
    name: "Xeno Forward Command",
    keywords: ["XENO"],
    cost: 9,
    vp: 9,
    powers: [],
    world: {
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-black-market-gangs.jpg",
    name: "Rebel Black Market Gangs",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["III", "$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-smuggling-post.jpg",
    name: "rebel smuggling post",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["III", "$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xc",
  },
  {
    src: "cards/star-nomad-lair.jpg",
    name: "Star Nomad Lair",
    cost: 1,
    vp: 1,
    powers: ["I", "$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/former-penal-colony.jpg",
    name: "Former Penal Colony",
    cost: 2,
    vp: 1,
    powers: ["III"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/pirate-world.jpg",
    name: "Pirate World",
    cost: 3,
    vp: 2,
    powers: ["$"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/xeno-hostage-planet.jpg",
    name: "Xeno Hostage Planet",
    keywords: ["XENO"],
    cost: 5,
    vp: 4,
    powers: [],
    world: {
      good: "NOVELTY",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/new-survivalists.jpg",
    name: "New Survivalists",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
      isMilitary: true,
    },
  },
  {
    src: "cards/rebel-bunker.jpg",
    name: "Rebel Bunker",
    keywords: ["REBEL"],
    cost: 1,
    vp: 0,
    powers: ["I", "III"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-fuel-cache.jpg",
    name: "Rebel Fuel Cache",
    keywords: ["REBEL"],
    cost: 1,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/runaway-robots.jpg",
    name: "Runaway Robots",
    cost: 1,
    vp: 1,
    powers: ["V"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/xeno-infested-imperium-cache.jpg",
    name: "xeno-infested imperium cache",
    keywords: ["XENO", "IMPERIUM"],
    cost: 4,
    vp: 2,
    powers: ["III"],
    world: {
      good: "RARE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xc",
  },
  {
    src: "cards/xeno-held-imperium-mine.jpg",
    name: "Xeno-Held Imperium Mine",
    keywords: ["IMPERIUM", "XENO"],
    cost: 2,
    vp: 0,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/rebel-miners.jpg",
    name: "Rebel Miners",
    keywords: ["REBEL"],
    cost: 2,
    vp: 1,
    powers: ["V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
  },
  {
    src: "cards/xeno-held-mining-colony.jpg",
    name: "xeno-held mining colony",
    keywords: ["XENO"],
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
    set: "xc",
  },
  {
    src: "cards/rebel-resistance.jpg",
    name: "Rebel Resistance",
    keywords: ["REBEL"],
    cost: 3,
    vp: 1,
    powers: ["I", "III", "V"],
    world: {
      good: "RARE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/the-last-of-the-uplift-gnarssh.jpg",
    name: "The Last of the Uplift Gnarssh",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 1,
    vp: 0,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/xeno-infested-uplift-world.jpg",
    name: "Xeno-Infested Uplift World",
    keywords: ["UPLIFT", "XENO", "CHROMO"],
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/avian-uplift-race.jpg",
    name: "Avian Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/reptilian-uplift-race.jpg",
    name: "Reptilian Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/aquatic-uplift-race.jpg",
    name: "Aquatic Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/arctic-uplift-race.jpg",
    name: "arctic uplift race",
    keywords: ["CHROMO", "UPLIFT"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xc",
  },
  {
    src: "cards/rebel-warrior-race.jpg",
    name: "Rebel Warrior Race",
    keywords: ["REBEL"],
    cost: 3,
    vp: 2,
    powers: ["III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/uplift-coalition.jpg",
    name: "Uplift Coalition",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 4,
    vp: "?",
    powers: ["I", "III"],
    world: {
      good: "GENE",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/xeno-occupied-genetics-labs.jpg",
    name: "xeno-occupied genetics labs",
    keywords: ["XENO"],
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "GENE",
      isMilitary: true,
    },
    set: "xc",
  },
  {
    src: "cards/xeno-colony.jpg",
    name: "Xeno Colony",
    keywords: ["XENO"],
    cost: 4,
    vp: 2,
    powers: ["V"],
    world: {
      good: "GENE",
      isMilitary: true,
    },
    set: "xi",
  },
  {
    src: "cards/malevolent-lifeforms.jpg",
    name: "Malevolent Lifeforms",
    cost: 4,
    vp: 2,
    powers: ["I", "V"],
    world: {
      good: "GENE",
      isMilitary: true,
    },
  },
  {
    src: "cards/anti-xeno-alien-trap.jpg",
    name: "anti-xeno alien trap",
    keywords: ["ANTI-XENO", "ALIEN"],
    cost: 1,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xc",
  },
  {
    src: "cards/alien-robot-sentry.jpg",
    name: "Alien Robot Sentry",
    keywords: ["ALIEN"],
    cost: 2,
    vp: 2,
    powers: [],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/alien-weapon-cache.jpg",
    name: "Alien Weapon Cache",
    keywords: ["ALIEN"],
    cost: 3,
    vp: 1,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/alien-robot-scout-ship.jpg",
    name: "Alien Robot Scout Ship",
    keywords: ["ALIEN"],
    cost: 4,
    vp: 2,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/lost-alien-warship.jpg",
    name: "Lost Alien Warship",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 3,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
  },
  {
    src: "cards/xeno-infested-alien-outpost.jpg",
    name: "Xeno-Infested Alien Outpost",
    keywords: ["ALIEN", "XENO"],
    cost: 7,
    vp: 5,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/alien-defense-center.jpg",
    name: "Alien Defense Center",
    keywords: ["ALIEN"],
    cost: 8,
    vp: 8,
    powers: ["III"],
    world: {
      good: "ALIEN",
      isMilitary: true,
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/lost-alien-battle-fleet.jpg",
    name: "Lost Alien Battle Fleet",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
      isMilitary: true,
    },
  },
  {
    src: "cards/pilgrimage-world.jpg",
    name: "Pilgrimage World",
    cost: 0,
    vp: 2,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/gambling-world.jpg",
    name: "Gambling World",
    cost: 1,
    vp: 1,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/expanding-colony.jpg",
    name: "Expanding Colony",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {},
  },
  {
    src: "cards/anti-xeno-imperium-ring.jpg",
    name: "anti-xeno imperium ring",
    keywords: ["ANTI-XENO", "IMPERIUM"],
    cost: 1,
    vp: 2,
    powers: ["III", "V"],
    world: {},
    set: "xc",
  },
  {
    src: "cards/black-market-trading-world.jpg",
    name: "Black Market Trading World",
    cost: 2,
    vp: 1,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/galactic-engineers.jpg",
    name: "Galactic Engineers",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {},
  },
  {
    src: "cards/alien-rosetta-stone-world.jpg",
    name: "Alien Rosetta Stone World",
    keywords: ["ALIEN"],
    cost: 3,
    vp: 3,
    powers: ["III", "V"],
    world: {},
  },
  {
    src: "cards/tourist-world.jpg",
    name: "Tourist World",
    cost: 4,
    vp: 2,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/merchant-world.jpg",
    name: "Merchant World",
    cost: 4,
    vp: 2,
    powers: ["$", "IV"],
    world: {},
  },
  {
    src: "cards/galactic-trendsetters.jpg",
    name: "Galactic Trendsetters",
    cost: 5,
    vp: 3,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/terraformed-world.jpg",
    name: "Terraformed World",
    cost: 5,
    vp: 5,
    powers: ["IV"],
    world: {},
  },
  {
    src: "cards/refugee-world.jpg",
    name: "Refugee World",
    cost: 0,
    vp: 1,
    powers: ["III"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
  },
  {
    src: "cards/novelty-peddlers.jpg",
    name: "Novelty Peddlers",
    cost: 2,
    vp: 1,
    powers: ["III", "$", "IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/galactic-resort.jpg",
    name: "Galactic Resort",
    cost: 3,
    vp: 2,
    powers: ["IV"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
  },
  {
    src: "cards/galactic-clearing-house.jpg",
    name: "Galactic Clearing House",
    cost: 5,
    vp: 3,
    powers: ["$", "IV", "V"],
    world: {
      good: "NOVELTY",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/uplift-descendants.jpg",
    name: "Uplift Descendants",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 1,
    vp: 0,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xi",
  },
  {
    src: "cards/artist-colony.jpg",
    name: "Artist Colony",
    cost: 1,
    vp: 1,
    powers: ["V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/secluded-world.jpg",
    name: "Secluded World",
    cost: 1,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/gem-world.jpg",
    name: "Gem World",
    cost: 2,
    vp: 1,
    powers: ["V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/spice-world.jpg",
    name: "Spice World",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/space-port.jpg",
    name: "Space Port",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/anti-xeno-pioneers.jpg",
    name: "anti-xeno pioneers",
    keywords: ["ANTI-XENO"],
    cost: 2,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xc",
  },
  {
    src: "cards/new-vinland.jpg",
    name: "New Vinland",
    cost: 2,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/anti-xeno-embassy.jpg",
    name: "Anti-Xeno Embassy",
    keywords: ["ANTI-XENO"],
    cost: 2,
    vp: 1,
    powers: ["III", "IV", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xi",
  },
  {
    src: "cards/prosperous-world.jpg",
    name: "Prosperous World",
    cost: 3,
    vp: 2,
    powers: ["IV", "V"],
    world: {
      good: "NOVELTY",
    },
  },
  {
    src: "cards/adaptable-uplift-settlers.jpg",
    name: "adaptable uplift settlers",
    keywords: ["CHROMO", "UPLIFT"],
    cost: 3,
    vp: 2,
    powers: ["III", "IV", "V"],
    world: {
      good: "NOVELTY",
    },
    set: "xc",
  },
  {
    src: "cards/destroyed-world.jpg",
    name: "Destroyed World",
    cost: 1,
    vp: 0,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/terraforming-uplift-project.jpg",
    name: "Terraforming Uplift Project",
    keywords: ["UPLIFT", "TERRAFORMING", "CHROMO"],
    cost: 2,
    vp: 0,
    powers: ["IV"],
    world: {
      good: "RARE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/asteroid-belt.jpg",
    name: "Asteroid Belt",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/radioactive-world.jpg",
    name: "Radioactive World",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/blaster-gem-mines.jpg",
    name: "Blaster Gem Mines",
    cost: 3,
    vp: 2,
    powers: ["III"],
    world: {
      good: "RARE",
      isWindfall: true,
    },
  },
  {
    src: "cards/bio-hazard-mining-world.jpg",
    name: "Bio-Hazard Mining World",
    cost: 2,
    vp: 0,
    powers: ["$", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/rare-elements-outcropping.jpg",
    name: "rare elements outcropping",
    cost: 3,
    vp: 1,
    powers: ["IV", "V"],
    world: {
      good: "RARE",
    },
    set: "xc",
  },
  {
    src: "cards/comet-zone.jpg",
    name: "Comet Zone",
    cost: 3,
    vp: 2,
    powers: ["V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/mining-world.jpg",
    name: "Mining World",
    cost: 3,
    vp: 2,
    powers: ["V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/imperium-armaments-world.jpg",
    name: "Imperium Armaments World",
    keywords: ["IMPERIUM"],
    cost: 3,
    vp: 2,
    powers: ["III", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/corrosive-uplift-world.jpg",
    name: "Corrosive Uplift World",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 3,
    vp: "?",
    powers: ["IV", "V"],
    world: {
      good: "RARE",
    },
    set: "xi",
  },
  {
    src: "cards/new-earth.jpg",
    name: "New Earth",
    cost: 5,
    vp: 3,
    powers: ["IV", "V"],
    world: {
      good: "RARE",
    },
  },
  {
    src: "cards/imperium-munitions-inc.jpg",
    name: "Imperium Munitions, Inc.",
    keywords: ["IMPERIUM"],
    cost: 5,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "RARE",
    },
    set: "xi",
  },
  {
    src: "cards/empath-world.jpg",
    name: "Empath World",
    cost: 1,
    vp: 1,
    powers: ["III"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
  },
  {
    src: "cards/anti-xeno-refugees.jpg",
    name: "Anti-Xeno Refugees",
    keywords: ["ANTI-XENO"],
    cost: 2,
    vp: 0,
    powers: ["III"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/pre-sentient-race.jpg",
    name: "Pre-Sentient Race",
    cost: 2,
    vp: 1,
    powers: [],
    world: {
      good: "GENE",
      isWindfall: true,
    },
  },
  {
    src: "cards/exotic-species-uplift-refuge.jpg",
    name: "exotic species uplift refuge",
    keywords: ["CHROMO", "UPLIFT"],
    cost: 3,
    vp: 2,
    powers: ["I", "IV"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
    set: "xc",
  },
  {
    src: "cards/adaptable-uplift-race.jpg",
    name: "Adaptable Uplift Race",
    keywords: ["UPLIFT", "CHROMO"],
    cost: 4,
    vp: 2,
    powers: ["IV"],
    world: {
      good: "GENE",
      isWindfall: true,
    },
    set: "xi",
  },
  {
    src: "cards/plague-world.jpg",
    name: "Plague World",
    cost: 3,
    vp: 0,
    powers: ["IV", "V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/pan-galactic-disease-center.jpg",
    name: "Pan-Galactic Disease Center",
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "GENE",
    },
    set: "xi",
  },
  {
    src: "cards/distant-world.jpg",
    name: "Distant World",
    cost: 4,
    vp: 2,
    powers: ["$", "V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/lost-species-ark-world.jpg",
    name: "Lost Species Ark World",
    cost: 5,
    vp: 3,
    powers: ["V"],
    world: {
      good: "GENE",
    },
  },
  {
    src: "cards/deserted-alien-outpost.jpg",
    name: "Deserted Alien Outpost",
    keywords: ["ALIEN"],
    cost: 4,
    vp: 3,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/deserted-alien-colony.jpg",
    name: "Deserted Alien Colony",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 4,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/deserted-alien-library.jpg",
    name: "Deserted Alien Library",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 5,
    powers: [],
    world: {
      good: "ALIEN",
      isWindfall: true,
    },
  },
  {
    src: "cards/anti-xeno-alien-bunker.jpg",
    name: "Anti-Xeno Alien Bunker",
    keywords: ["ANTI-XENO", "ALIEN"],
    cost: 3,
    vp: 1,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
    },
    set: "xi",
  },
  {
    src: "cards/alien-archives.jpg",
    name: "Alien Archives",
    keywords: ["ALIEN"],
    cost: 5,
    vp: 4,
    powers: ["III", "V"],
    world: {
      good: "ALIEN",
    },
    set: "xi",
  },
  {
    src: "cards/alien-robotic-factory.jpg",
    name: "Alien Robotic Factory",
    keywords: ["ALIEN"],
    cost: 6,
    vp: 5,
    powers: ["V"],
    world: {
      good: "ALIEN",
    },
  },
  {
    src: "cards/alien-shimmer-disk-cache.jpg",
    name: "alien shimmer disk cache",
    keywords: ["ALIEN"],
    cost: 7,
    vp: 4,
    powers: ["III", "IV", "V"],
    world: {
      good: "ALIEN",
    },
    set: "xc",
  },
  {
    src: "cards/scorched-earth-defense.jpg",
    name: "scorched-earth defense",
    cost: 1,
    vp: -1,
    powers: ["II", "III", "IV"],
    set: "xc",
  },
  {
    src: "cards/anti-xeno-militia.jpg",
    name: "Anti-Xeno Militia",
    keywords: ["ANTI-XENO"],
    cost: 1,
    vp: 0,
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/public-works.jpg",
    name: "Public Works",
    cost: 1,
    vp: 1,
    powers: ["II", "IV"],
  },
  {
    src: "cards/expedition-force.jpg",
    name: "Expedition Force",
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
  },
  {
    src: "cards/export-duties.jpg",
    name: "Export Duties",
    cost: 1,
    vp: 1,
    powers: ["$"],
  },
  {
    src: "cards/new-military-tactics.jpg",
    name: "New Military Tactics",
    cost: 1,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/contact-specialist.jpg",
    name: "Contact Specialist",
    cost: 1,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/investment-credits.jpg",
    name: "Investment Credits",
    cost: 1,
    vp: 1,
    powers: ["II"],
  },
  {
    src: "cards/alien-weapon-plans.jpg",
    name: "Alien Weapon Plans",
    keywords: ["ALIEN"],
    cost: 1,
    vp: 1,
    powers: ["I", "III"],
    set: "xi",
  },
  {
    src: "cards/colony-ship.jpg",
    name: "Colony Ship",
    cost: 2,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/mining-robots.jpg",
    name: "Mining Robots",
    cost: 2,
    vp: 1,
    powers: ["III", "V"],
  },
  {
    src: "cards/space-marines.jpg",
    name: "Space Marines",
    cost: 2,
    vp: 1,
    powers: ["III"],
  },
  {
    src: "cards/deficit-spending.jpg",
    name: "Deficit Spending",
    cost: 2,
    vp: 1,
    powers: ["IV"],
  },
  {
    src: "cards/interstellar-bank.jpg",
    name: "Interstellar Bank",
    cost: 2,
    vp: 1,
    powers: ["II"],
  },
  {
    src: "cards/genetics-lab.jpg",
    name: "Genetics Lab",
    cost: 2,
    vp: 1,
    powers: ["$", "V"],
  },
  {
    src: "cards/uplift-terraforming.jpg",
    name: "Uplift Terraforming",
    keywords: ["UPLIFT", "TERRAFORMING"],
    cost: 2,
    vp: 1,
    powers: ["I", "III", "V"],
    set: "xi",
  },
  {
    src: "cards/mining-conglomerate.jpg",
    name: "Mining Conglomerate",
    cost: 3,
    vp: 2,
    powers: ["$", "IV", "V"],
  },
  {
    src: "cards/terraforming-robots.jpg",
    name: "Terraforming Robots",
    keywords: ["TERRAFORMING"],
    cost: 3,
    vp: 2,
    powers: ["III", "IV"],
  },
  {
    src: "cards/anti-xeno-assault-troops.jpg",
    name: "Anti-Xeno Assault Troops",
    keywords: ["ANTI-XENO"],
    cost: 3,
    vp: 2,
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/terraforming-resettlement.jpg",
    name: "terraforming resettlement",
    keywords: ["TERRAFORMING"],
    cost: 3,
    vp: 2,
    powers: ["III", "IV"],
    set: "xc",
  },
  {
    src: "cards/diversified-economy.jpg",
    name: "Diversified Economy",
    cost: 4,
    vp: 2,
    powers: ["IV", "V"],
  },
  {
    src: "cards/research-labs.jpg",
    name: "Research Labs",
    cost: 4,
    vp: 2,
    powers: ["I", "IV", "V"],
  },
  {
    src: "cards/drop-ships.jpg",
    name: "Drop Ships",
    cost: 4,
    vp: 2,
    powers: ["III"],
  },
  {
    src: "cards/replicant-robots.jpg",
    name: "Replicant Robots",
    cost: 4,
    vp: 2,
    powers: ["III"],
  },
  {
    src: "cards/imperium-arms-factory.jpg",
    name: "Imperium Arms Factory",
    keywords: ["IMPERIUM"],
    cost: 4,
    vp: 2,
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/construction-corps.jpg",
    name: "Construction Corps",
    cost: 4,
    vp: 2,
    powers: ["II", "V"],
    set: "xi",
  },
  {
    src: "cards/consumer-markets.jpg",
    name: "Consumer Markets",
    cost: 5,
    vp: 3,
    powers: ["IV", "V"],
  },
  {
    src: "cards/galactic-home-front.jpg",
    name: "Galactic Home Front",
    cost: 5,
    vp: 3,
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-arsenal.jpg",
    name: "anti-xeno arsenal",
    keywords: ["ANTI-XENO"],
    cost: 5,
    vp: 3,
    powers: ["III", "V"],
    set: "xc",
  },
  {
    src: "cards/pan-galactic-league.jpg",
    name: "Pan-Galactic League",
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
  },
  {
    src: "cards/mining-league.jpg",
    name: "Mining League",
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
  },
  {
    src: "cards/free-trade-association.jpg",
    name: "Free Trade Association",
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
  },
  {
    src: "cards/alien-tech-institute.jpg",
    name: "Alien Tech Institute",
    keywords: ["ALIEN"],
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/galactic-survey-seti.jpg",
    name: "Galactic Survey: SETI",
    cost: 6,
    vp: "?",
    powers: ["I"],
  },
  {
    src: "cards/galactic-federation.jpg",
    name: "Galactic Federation",
    cost: 6,
    vp: "?",
    powers: ["II"],
  },
  {
    src: "cards/new-galactic-order.jpg",
    name: "New Galactic Order",
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/merchant-guild.jpg",
    name: "Merchant Guild",
    cost: 6,
    vp: "?",
    powers: ["V"],
  },
  {
    src: "cards/new-economy.jpg",
    name: "New Economy",
    cost: 6,
    vp: "?",
    powers: ["IV"],
  },
  {
    src: "cards/galactic-renaissance.jpg",
    name: "Galactic Renaissance",
    cost: 6,
    vp: "?",
    powers: ["I"],
  },
  {
    src: "cards/galactic-imperium.jpg",
    name: "Galactic Imperium",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: "?",
    powers: ["III"],
  },
  {
    src: "cards/trade-league.jpg",
    name: "Trade League",
    cost: 6,
    vp: "?",
    powers: ["$"],
  },
  {
    src: "cards/uplift-bio-engineers.jpg",
    name: "Uplift Bio-Engineers",
    keywords: ["UPLIFT"],
    cost: 6,
    vp: "?",
    powers: ["IV", "V"],
    set: "xi",
  },
  {
    src: "cards/imperium-war-profiteers.jpg",
    name: "Imperium War Profiteers",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
    set: "xi",
  },
  {
    src: "cards/terraforming-defenders.jpg",
    name: "Terraforming Defenders",
    keywords: ["TERRAFORMING"],
    cost: 6,
    vp: "?",
    powers: ["III", "IV", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-rebel-force.jpg",
    name: "Anti-Xeno Rebel Force",
    keywords: ["ANTI-XENO", "REBEL"],
    cost: 6,
    vp: "?",
    powers: ["III"],
    set: "xi",
  },
  {
    src: "cards/alien-historians.jpg",
    name: "Alien Historians",
    keywords: ["ALIEN"],
    cost: 6,
    vp: "?",
    powers: ["I", "III", "V"],
    set: "xi",
  },
  {
    src: "cards/anti-xeno-league.jpg",
    name: "Anti-Xeno League",
    keywords: ["ANTI-XENO"],
    cost: 6,
    vp: "?",
    powers: ["III", "V"],
    set: "xi",
  },
  {
    src: "cards/frontier-isolationists.jpg",
    name: "frontier isolationists",
    cost: 6,
    vp: "?",
    powers: ["I", "III"],
    set: "xc",
  },
  {
    src: "cards/imperium-expansionists.jpg",
    name: "imperium expansionists",
    keywords: ["IMPERIUM"],
    cost: 6,
    vp: "?",
    powers: ["II", "III", "IV"],
    set: "xc",
  },
  {
    src: "cards/rebel-smugglers.jpg",
    name: "rebel smugglers",
    keywords: ["REBEL"],
    cost: 6,
    vp: "?",
    powers: ["I", "III", "IV"],
    set: "xc",
  },
  {
    src: "cards/terraforming-refugees.jpg",
    name: "terraforming refugees",
    keywords: ["TERRAFORMING"],
    cost: 6,
    vp: "?",
    powers: ["II", "III", "V"],
    set: "xc",
  },
  {
    src: "cards/uplift-pioneers.jpg",
    name: "uplift pioneers",
    keywords: ["UPLIFT"],
    cost: 6,
    vp: "?",
    powers: ["I", "III", "V"],
    set: "xc",
  },
  {
    src: "cards/anti-xeno-alien-warships.jpg",
    name: "anti-xeno alien warships",
    keywords: ["ANTI-XENO", "ALIEN"],
    cost: 7,
    vp: 5,
    powers: ["III"],
    set: "xc",
  },
  {
    src: "cards/anti-xeno-armada.jpg",
    name: "anti-xeno armada",
    keywords: ["ANTI-XENO"],
    cost: 9,
    vp: 7,
    powers: ["III"],
    set: "xc",
  },
];
